# Use root/12346 as user/password credentials

version: '3.1'

services:
    mysql_master: &mysql
        image: mysql:${TAG}
        container_name: mysql_master
        hostname: mysql_master
        env_file:
            - env/base.env
            - env/master.env
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./conf:/etc/mysql/conf.d  # 配置文件
            - ./docker_app/data/master:/var/lib/mysql # 数据存储
            - ./docker_app/logs/master:/var/log/mysql # 日志
            #- ./init_db_sql/sakila-schema.sql:/docker-entrypoint-initdb.d/0-sakila-schema.sql
            #- ./init_db_sql/init-test.sh:/docker-entrypoint-initdb.d/1-init-test.sh # 初始化sql
            - ./init_db_sql/init-master.sh:/docker-entrypoint-initdb.d/2-init-master.sh # 初始化sql
        command: [
            "--log-bin=mysql-bin",
            "--server-id=${MASTER_SERVER_ID}",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--innodb_flush_log_at_trx_commit=1",
            "--sync_binlog=1",
            "--default-authentication-plugin=mysql_native_password"
            ]

    mysql_slave1: &mysql_node
        <<: *mysql
        container_name: mysql_slave1
        hostname: mysql_slave1
        env_file:
            - env/base.env
            - env/node.env
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MASTER_MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./conf:/etc/mysql/conf.d  # 配置文件
            - ./docker_app/data/slave1:/var/lib/mysql # 数据存储
            - ./docker_app/logs/slave1:/var/log/mysql # 日志
            #- ./init_db_sql/sakila-schema.sql:/docker-entrypoint-initdb.d/0-sakila-schema.sql
            - ./init_db_sql/init-node.sh:/docker-entrypoint-initdb.d/1-init-node.sh
        command: [
            "--server-id=${NODE_1_SERVER_ID}",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-authentication-plugin=mysql_native_password"
            ]

    mysql_slave2:
        <<: *mysql_node
        container_name: mysql_slave2
        hostname: mysql_slave2
        ports:
            - 3308:3306
        volumes:
            - ./conf:/etc/mysql/conf.d  # 配置文件
            - ./docker_app/data/slave2:/var/lib/mysql # 数据存储
            - ./docker_app/logs/slave2:/var/log/mysql # 日志
            #- ./init_db_sql/sakila-schema.sql:/docker-entrypoint-initdb.d/0-sakila-schema.sql
            - ./init_db_sql/init-node.sh:/docker-entrypoint-initdb.d/1-init-node.sh
        command: [
            "--server-id=${NODE_2_SERVER_ID}",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-authentication-plugin=mysql_native_password"
            ]

    adminer:
        image: adminer
        container_name: mysql_adminer
        restart: always
        links:
            - mysql_master:master
        ports:
            - 48080:8080